//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public int Empid { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Address { get; set; }
        public string Department { get; set; }
        public Nullable<long> AdharNo { get; set; }
        public Nullable<long> Contactno { get; set; }
        public Nullable<int> pincode { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
    }
}
